### ISSUE TITLE
napari layer Union support

### ISSUE THREAD

**Issue by ch-n** [napari/magicgui#400] opened 2022-04-27 14:30 UTC
Thanks a lot for the nice work your doing.
It is really useful that magicgui automatically generates selection drop-downs for napari viewer layers if one uses type annotations.
`def foo(layer: napari.layers.Iamge)`

I would like to call for the addition of support for a Union (as in `typing`) of different layer types during type annotation detection.
`def foo(layer: Union[napari.layers.Image, napari.layers.Labels])`

I can imagine several use cases were one would like to access multiple layer types from the viewer such as image and labels. Thus, if it is not to complicated to implement it might be a useful feature.

**Comment by tlambert03** [comment] 2022-04-27 15:08
Thanks @ch-n ... this is more or less a duplicate of https://github.com/napari/magicgui/issues/93  (the napari-specific part isn't anything additionally special, magicgui itself doesn't "know" about napari).

I'm going to close this since there's already an open issue for it.  Feel free to comment over there though

**Closed by tlambert03** 2022-04-27 15:08 UTC
