### ISSUE TITLE
PushButtons not working with PySide2

### ISSUE THREAD

**Issue by pmascalchi** [napari/magicgui#341] opened 2021-12-30 23:41 UTC
**Describe the bug**
Using the 'widget_demo.py' file, I can't get the 'calculate' button to work.
I also see no window popping up with the file picker.
To be more sure I was not messing up with some packages, I installed python 3.9 from scratch again and tried to run the demo file after installing some few base packages.
I tried to run the code from command-line or PyCharm, both leading to the same result.

**To Reproduce**
1. Run the 'widget_demo.py' script from command-line, which is this one:
https://github.com/napari/magicgui/blob/main/examples/widget_demo.py
2. Change values and see that the updated values are printed (code is functional and change.connect is also ok)
3. Try to press the 'Select File' button >> nothing happens
4. Try to press the 'Calculate' button >> nothing happens
No message can be seen in the console...

**Expected behavior**
'Select File' button would open a dialog window to select a file.
'Calculate' button would show values in the result box.

**Screenshots**
![image](https://user-images.githubusercontent.com/18047969/147794510-a8d08b43-9c7d-4fe0-9edb-a23e8a46af71.png)

**Environment**
 - OS: Win 10 Pro, 21H1, build 19043.1348
 - backend: PySide2 5.15.2
 - magicgui version: 0.3.3
 - Python 3.9

site-packages:
docstring-parser==0.13
et-xmlfile==1.1.0
imagecodecs==2021.11.20
imageio==2.13.5
magicgui==0.3.3
networkx==2.6.3
numpy==1.21.5
openpyxl==3.0.9
packaging==21.3
pandas==1.3.5
Pillow==8.4.0
psygnal==0.2.0
pyparsing==3.0.6
PySide2==5.15.2
python-dateutil==2.8.2
pytz==2021.3
PyWavelets==1.2.0
QtPy==2.0.0
scikit-image==0.19.1
scipy==1.7.3
shiboken2==5.15.2
SimpleITK==2.1.1
six==1.16.0
tifffile==2021.11.2
typing-extensions==4.0.1

**Comment by pmascalchi** [comment] 2021-12-30 23:45
PS: I was previously using magicgui 0.1.6 [PySide2] in Python 3.6, where I had no issues with file picker and call button...

**Comment by tlambert03** [comment] 2021-12-31 02:46
Hi, I just tried this on main and was not able to reproduce it.  however, I was able to reproduce it if I checkout v0.3.3 (the version currently on pypi).  I suspect it was fixed by https://github.com/napari/magicgui/pull/331

If you can confirm by checking main that would be great (`pip install -U git+https://github.com/napari/magicgui.git`)

**Comment by pmascalchi** [comment] 2021-12-31 10:50
Hi, thanks for your quick reply. I did the upgrade but still get the same behavior.

![image](https://user-images.githubusercontent.com/18047969/147819161-648689ab-3123-4d77-ab3f-d8d3ddd536ce.png)

**Comment by pmascalchi** [comment] 2021-12-31 11:10
Same issue with this code, but at this point, I believe it's not surprising:

```
from magicgui.widgets import SpinBox, FileEdit, Slider, Label, Container
from pathlib import Path

# make some widgets
spin_box = SpinBox(value=10, name='spin', label='Value:', max=100)
file_picker = FileEdit(value=Path.home())
slider = Slider(value=30, min=20, max=40)
label = Label(value=slider.value)


# set up callbacks
@slider.changed.connect
def set_label(value: str):
    label.value = value


# create a container to hold the widgets:
container = Container(widgets=[spin_box, file_picker, slider, label])
container.show(run=True)
```

**Comment by tlambert03** [comment] 2021-12-31 22:32
was eventually able to reproduce, but it looks specific to PySide2.  need to take a look to see what's going on there, but until the next magicgui release, if you use pyqt5 you should be able to push forward for now.

**Comment by tlambert03** [comment] 2021-12-31 22:52
looks like this is just a general problem with pushbuttons on pyside2!  I'm really surprised this hasn't popped up already, and isn't being caught by the tests.  here's the minimal code to reproduce:

```py
from magicgui.widgets import PushButton
btn = PushButton(text='click me')
btn.changed.connect(lambda: print('clicked'))
btn.show(run=True)
```

**Closed** 2022-01-01 17:02 UTC
Labels: bug

**Comment by pmascalchi** [comment] 2022-01-01 17:16
Nice work! Thanks a lot!!
Wishing you great things for this new year!

**Comment by tlambert03** [comment] 2022-01-01 17:42
thanks a lot for reporting.  can't believe this was in there 😬 

0.3.4 is released with this bugfix
